### ISSUE TITLE
Is there a way to inject JSON:API filters?

### ISSUE THREAD

**Issue by Redsandro** [stonecircle/express-autoroute-json#28]
I'm afraid I couldn't figure this out from the documentation or the source code.

Am I correct that there is no [filter logic](https://jsonapi.org/format/#fetching-filtering) in this module?

JsonAPI manual:
> JSON:API is agnostic about the strategies supported by a server. The filter query parameter can be used as the basis for any number of filtering strategies.

Is there a place to inject custom filter logic? I have to admit that I'm used to working with MongoDb directly, and I'm new to `mongoose`. So I'm not sure if this is built into mongoose and/or I should look at the mongoose module for this type of question.

For a viable json:api adapter we need to be able to respond to sorting and filtering queues.

* `sort` with custom modifiers
* `page` with custom logic
* `filter` with custom modifiers

**Example:** 

```javascript
function getFilterKey(el) {
  if (!el.operator) return el.value
  return {
    '>': { $gt: el.value },
    '<': { $lt: el.value },
    '~': new RegExp(`^${el.value}$`, 'i'),
    ':': new RegExp(el.value, 'i')
  }[el.operator]
}
```

**Comment by mansona** [comment]
Yes this does support filtering 😄 

The relivant documentation is here: https://github.com/stonecircle/express-autoroute-json/wiki/Find-Query and there is more information here if that doesn't help: https://beginner-guides.authmaker.com/release/customize-routes/query/

Does that help?

(For the record documentation is the single worst thing about this project so any feedback or help you can give on that regard would be well recieved)

**Comment by Redsandro** [comment]
Ah thank you! This is what I am looking for.
I think maybe we should add some sane defaults.

**Comment by mansona** [comment]
My logic was that the filter behaivour is relivant to **your** specific business logic.

I am happy to re-consider this assumption at a later date 👍

**Comment by Redsandro** [comment]
@mansona you are very right! Overridable and extendable sane defaults might be a big speed-up when writing a backend though. :smiley: 

Are you open to pull requests?
